@startuml
' left to right direction
' skinparam linetype polyline

'' Classes
class DOM
class Character{
    x : int
    y : int
    characterWidth : int
    characterHeight : int
}
class CharacterDraw{
    formBasicShape()
    draw()
}
class EventListenerHandler{
    inputDocument : DOM
    playerInput : PlayerInput
    AddKeypressEventListener()
    AddClickEventListener()
    clickHandler()
    keyPressHandler()
}
class PlayerInput{
    playerInputList : Array
    isProccessed : boolean
    initialize()
}
class PlayerInputProcessor{
    character : Character
    playerInput : PlayerInput
    process()
}
class PlayerAction{

}
'' relationship
CharacterDraw --up-> Character 
EventListenerHandler --up-> PlayerInput
EventListenerHandler --up-> DOM
PlayerInputProcessor --up-> PlayerInput
PlayerInputProcessor  --up-> Character

' layout
' DOM -[hidden]- PlayerInput
' DOM -[hidden]- PlayerInput
' DOM -[hidden]- PlayerInput
' DOM -[hidden]- PlayerInput
' DOM -[hidden]- PlayerInput
' Character -[hidden]- DOM
' Character -[hidden]- DOM
' Character -[hidden]- DOM
' Character -[hidden]- DOM
' DOM -[hidden]- DOM
' CharacterDraw -right[hidden]- PlayerInputProcessor
' PlayerInputProcessor -left[hidden]- CharacterDraw
' PlayerInputProcessor -left[hidden]- CharacterDraw
' PlayerInputProcessor -left[hidden]- CharacterDraw
' EventListenerHandler -[hidden]- PlayerInputProcessor
@enduml