@startuml
participant "Player:Character" as Player
participant ContourSkeleton
participant CollisionContours


[-> Player : new
activate Player
Player -> Player ++: intitializeContours()
Player -> Player ++: new <color #118888>points</color>: Array<Point>()
deactivate Player
Player -> ContourSkeleton ++: new <color #42f590>skeleton</color>: ContourSkeleton(<color #118888>points</color>)
deactivate ContourSkeleton
Player -> Player ++: new <color #0000FF>formulas</color>(ContourSkeleton)
deactivate Player
Player -> CollisionContours ++: new CollisionContours(<color #42f590>skeleton</color>, <color #0000FF>formulas</color>)
deactivate CollisionContours
deactivate Player

@enduml